### ISSUE TITLE
Create quick-share options

### ISSUE THREAD

**Issue by josephatkuvio** [sparc-coop/law-of-100#12]

**Comment by josephatkuvio** [comment]
Can we share an image? (check card sharing options across platforms)

**Comment by kprkr** [comment]
### Reasons for a share
- Individual to share progress & feel obligated/motivated
- For us to reach more individuals

### How to do this through share
- Share progress
- Motivate others to do the same
- Persuade individuals to "Cheer $user along their journey"

**Comment by josephatkuvio** [comment]
Geeky observation from me just now: A "share" is just a push notification to all the Law of 100 user's friends 🤔May come in handy from an architecture perspective...
