### ISSUE TITLE
After CreateHabit, float the grid up and *change* it to the habit page

### ISSUE THREAD

**Issue by josephatkuvio** [sparc-coop/law-of-100#17]

**Comment by josephatkuvio** [comment]
@kprkr how should the actual title text change? Also is the flow like this...

Habit is created
Grid floats up (over the form?)
Title text changes to the specific habit

If so, then @JParker443 I wonder if we can "fake" this by doing the float-up animation on the Create page, then actually redirecting to the /habits/123 individual habit page but making sure that the grid is pixel-perfect in exactly the same place as it ended up on the Create page?

**Comment by kprkr** [comment]
Good question. 

I'll create a storyboard of some type
