### ISSUE TITLE
When does a new day end and new day start, and do we stop people "cheating" the time?

### ISSUE THREAD

**Issue by kprkr** [sparc-coop/law-of-100#29]
A question to tackle (that maybe simple/obvious) is how do we treat a new day/when does it start.
I assume midnight local time, but where do we get local time?

If from their PC, they could technically turn back time to edit days?
If server, do we need to allow them to set their local time? And, if so, do we allow them to edit it? What repercussions would that have?

**Comment by josephatkuvio** [comment]
My initial thoughts here is that a "day" (when it starts, etc.) won't matter as much, if we stick with the recurrence idea we're currently working with (i.e. X time has passed, rather than using a specific local time). But I'll keep this in mind as I architect it, and we'll see where it takes us!
