### ISSUE TITLE
Create recurrence options in UI and CreateHabit

### ISSUE THREAD

**Issue by josephatkuvio** [sparc-coop/law-of-100#4]

**Comment by josephatkuvio** [comment]
Potential source to pull from: https://stackoverflow.com/questions/9821511/calculating-recurrence-of-events-using-datetime-in-c-sharp

**Comment by josephatkuvio** [comment]
From @lauraferraz5 : what happens when they try to track a day they haven't chosen on the custom days list? How does recurrence affect the app?

**Comment by josephatkuvio** [comment]
What about having a "velocity" idea, where the "system" marks an X after X time, that X time somehow visible to the user so they know what they're "fighting" against -- i.e., at what point they need to log on and register their successful day, so the X doesn't occur?

**Comment by josephatkuvio** [comment]
Thinking more about this "velocity" idea... we would basically also need a numerical "fudge factor", like 20% or something, so that for example, a "every 3 days or so" habit won't be X'd off by the system until 3 days PLUS 20% has passed. @kprkr I wonder if this should be a user-editable number as well, or if we should make it "friendlier" (i.e. aggressive, lots of leeway, average as options) or hide it altogether and just do the fudge factor in the background.

**Comment by josephatkuvio** [comment]
@JParker443 @lauraferraz5 I created branch feature/recurrence with my initial thoughts on the recurrence algorithm. It's very simple -- it takes a number of hours (24 for 1 day for example) and a "fudge factor" (defaulting to 0.5 or 50%) and figures out if the habit is "overdue" or not based on that fudge factor. Then it enters an "unsuccessful progression" into 

I haven't tested this yet, but hopefully once we get the Progressions creating, it will be close enough to working with just a few tweaks! (or maybe it's a bad idea altogether)

**Comment by kprkr** [comment]
I really like the idea of having a friendly "fudge number" displaying something like "How strict would you like this rule?" and having very human answers.

Relaxed (X days + 50%) / Standard (x days + 25% )/ Strict (x days + 10%).

We could also have an "info" icon next to these that label them in more detail.

**Comment by josephatkuvio** [comment]
Figma spec is ready, so I'll be working on this in the next couple of days to implement it.
